// ---------------------------------------------------------------------------
// Image Provenance Tracking
//
// Records which Venice image model(s) produced a given PNG on disk. Seedance
// 2.0 blocks any video request whose input images were generated by a
// non-compatible family (currently only `seedream-v5-lite` /
// `seedream-v5-lite-edit` are accepted). The provenance sidecar lets the
// pre-flight gate detect these before the request reaches Venice.
//
// Storage format
// --------------
// For `/path/to/shot-003.png` we write `/path/to/shot-003.provenance.json`:
//
//   {
//     "generationModel": "seedream-v5-lite",
//     "editModels": ["seedream-v5-lite-edit"],
//     "createdAt": "2026-04-17T12:00:00.000Z",
//     "updatedAt": "2026-04-17T12:05:00.000Z"
//   }
//
// Images without a sidecar are treated as "unknown" — the pre-flight gate
// prompts the user rather than silently letting the request through.
// ---------------------------------------------------------------------------

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname } from 'node:path';
import {
  SEEDANCE_COMPATIBLE_GENERATION_MODELS,
  SEEDANCE_COMPATIBLE_EDIT_MODELS,
} from '../series/types.js';

// ---- Types ----------------------------------------------------------------

export interface ImageProvenance {
  /** The model that produced the first version of this image. */
  generationModel: string;
  /** Ordered list of edit models applied to the image. */
  editModels: string[];
  createdAt: string;
  updatedAt: string;
}

export interface ProvenanceCheckResult {
  /** True if every input image is Seedance-compatible (or has no provenance). */
  compatible: boolean;
  /** Images that cannot be sent to Seedance with their current provenance. */
  incompatible: Array<{
    imagePath: string;
    provenance: ImageProvenance | 'unknown';
    reason: string;
  }>;
}

// ---- Path helpers ---------------------------------------------------------

function sidecarPath(imagePath: string): string {
  // Replace the image extension with .provenance.json
  return imagePath.replace(/\.(png|jpg|jpeg|webp)$/i, '.provenance.json');
}

// ---- Read / write ---------------------------------------------------------

export async function readImageProvenance(
  imagePath: string,
): Promise<ImageProvenance | null> {
  const sidecar = sidecarPath(imagePath);
  if (!existsSync(sidecar)) return null;
  try {
    const raw = await readFile(sidecar, 'utf-8');
    return JSON.parse(raw) as ImageProvenance;
  } catch {
    return null;
  }
}

export async function writeImageProvenance(
  imagePath: string,
  generationModel: string,
  editModels: string[] = [],
): Promise<void> {
  const sidecar = sidecarPath(imagePath);
  await mkdir(dirname(sidecar), { recursive: true });

  const existing = await readImageProvenance(imagePath);
  const now = new Date().toISOString();

  const next: ImageProvenance = {
    generationModel: existing?.generationModel ?? generationModel,
    editModels: [...(existing?.editModels ?? []), ...editModels],
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
  };

  await writeFile(sidecar, JSON.stringify(next, null, 2), 'utf-8');
}

/**
 * Record that an edit model was applied on top of an existing provenance
 * record. If no provenance exists yet, the editModel becomes the generation
 * model (the image is effectively fresh from that edit pass).
 */
export async function recordEditProvenance(
  imagePath: string,
  editModel: string,
): Promise<void> {
  const existing = await readImageProvenance(imagePath);
  if (!existing) {
    await writeImageProvenance(imagePath, editModel, []);
    return;
  }
  await writeImageProvenance(imagePath, existing.generationModel, [editModel]);
}

// ---- Seedance compatibility -----------------------------------------------

/**
 * Check whether an image's provenance makes it safe to send to Seedance 2.0.
 *
 * Rules (as of April 2026):
 * - The generation model must be in SEEDANCE_COMPATIBLE_GENERATION_MODELS, OR
 * - The most recent edit must be in SEEDANCE_COMPATIBLE_EDIT_MODELS.
 *
 * A missing sidecar is treated as non-compatible: we have no evidence the
 * image came from a seedream model, so the pre-flight gate must surface it.
 */
export function isSeedanceCompatibleProvenance(
  prov: ImageProvenance | null,
): boolean {
  if (!prov) return false;
  if (SEEDANCE_COMPATIBLE_GENERATION_MODELS.has(prov.generationModel)) return true;
  const lastEdit = prov.editModels[prov.editModels.length - 1];
  if (lastEdit && SEEDANCE_COMPATIBLE_EDIT_MODELS.has(lastEdit)) return true;
  return false;
}

/**
 * Verify every image on disk at the supplied paths. Returns a structured
 * result listing any incompatible images so the caller can prompt / fallback
 * / launder.
 *
 * Paths that are not on-disk files (data: URIs, http URLs) are ignored — we
 * only have provenance for images we wrote ourselves.
 */
export async function checkImagesForSeedance(
  imagePaths: Array<string | undefined>,
): Promise<ProvenanceCheckResult> {
  const incompatible: ProvenanceCheckResult['incompatible'] = [];

  for (const path of imagePaths) {
    if (!path) continue;
    if (path.startsWith('data:') || path.startsWith('http')) continue;
    if (!existsSync(path)) continue;

    const prov = await readImageProvenance(path);
    const compatible = isSeedanceCompatibleProvenance(prov);
    if (compatible) continue;

    if (!prov) {
      incompatible.push({
        imagePath: path,
        provenance: 'unknown',
        reason: 'No provenance sidecar — generation model is unknown.',
      });
      continue;
    }

    const lastEdit = prov.editModels[prov.editModels.length - 1];
    const surface = lastEdit ? `${prov.generationModel} + ${lastEdit}` : prov.generationModel;
    incompatible.push({
      imagePath: path,
      provenance: prov,
      reason: `Generated by ${surface}; Seedance only accepts seedream-v5-lite / seedream-v5-lite-edit.`,
    });
  }

  return { compatible: incompatible.length === 0, incompatible };
}
